repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.8
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: 'master'  # Use the revision sha / tag you want to point at
    hooks:
      - id: isort
